# Generated by Django 5.2.6 on 2025-12-09 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeequipe', models.CharField(max_length=20, verbose_name='Seleção')),
                ('continente', models.CharField(max_length=20, verbose_name='Continente')),
                ('nometecnico', models.CharField(max_length=50, verbose_name='Técnico')),
                ('grupo', models.CharField(max_length=1, verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Seleção',
                'verbose_name_plural': 'Seleções',
            },
        ),
        migrations.CreateModel(
            name='Estadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadio', models.CharField(max_length=50, verbose_name='Nome do Estádio')),
                ('cidade', models.CharField(max_length=20, verbose_name='Cidade')),
                ('UF', models.CharField(max_length=5, verbose_name='UF')),
                ('capacidade', models.IntegerField(verbose_name='Capacidade')),
            ],
            options={
                'verbose_name': 'Estádio',
                'verbose_name_plural': 'Estádios',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do jogador')),
                ('clube', models.CharField(max_length=20, verbose_name='Clube')),
                ('posicao', models.CharField(max_length=20, verbose_name='Posição')),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.equipe')),
            ],
            options={
                'verbose_name': 'Jogador',
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data da partida')),
                ('gols_mandante', models.IntegerField(default=0)),
                ('gols_visitante', models.IntegerField(default=0)),
                ('estadio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='app.estadio')),
                ('mandante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_mandante', to='app.equipe')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='app.equipe')),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField()),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='app.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols', to='app.partida')),
            ],
        ),
    ]
